makefile: add check-place and check-route
Empty reports are generated if there are no errors.

This supports the Bazel use-case to create artifacts for inspection
in the case that detailed place, global place,
global route or detailed route fails.

Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>

diff --git a/flow/Makefile b/flow/Makefile
--- a/flow/Makefile
+++ b/flow/Makefile
@@ -659,10 +659,42 @@ $(eval $(call do-copy,3_place,3_5_place_dp.odb,))
 
 $(eval $(call do-copy,3_place,2_floorplan.sdc,,.sdc))
 
+# This target does not produce a non-zero exit code if detailed or global
+# placement fails. In this case $(RESULTS_DIR)/3_place.odb and $(RESULTS_DIR)/3_place.sdc
+# are produced, such that an artifact can be created for inspection purposes.
+#
+# The check-place target subsequently will fail if
+# placement did not complete successfully, because $(RESULTS_DIR)/place.ok
+# is set to 0.
+#
+# This means that build systems, such as Bazel, that require a non-zero
+# exit code and the same artifacts to be produced every time, or it
+# will not publish the artifacts, can use this target.
 .PHONY: do-place
 do-place:
 	mkdir -p $(LOG_DIR) $(REPORTS_DIR)
-	$(UNSET_AND_MAKE) do-3_1_place_gp_skip_io do-3_2_place_iop do-3_3_place_gp do-3_4_place_resized do-3_5_place_dp do-3_place do-3_place.sdc
+	echo >$(RESULTS_DIR)/place.ok 0
+	$(UNSET_AND_MAKE) do-3_1_place_gp_skip_io do-3_2_place_iop
+	@$(UNSET_VARS); \
+	$(SUB_MAKE) WRITE_ON_FAIL=1 do-3_3_place_gp; \
+	if [ $$? -ne 0 ]; then \
+		cp $(RESULTS_DIR)/3_3_place_gp.odb $(RESULTS_DIR)/3_place.odb ; \
+		$(SUB_MAKE) do-3_place.sdc ; \
+	else \
+		$(SUB_MAKE) do-3_4_place_resized ; \
+		$(SUB_MAKE) WRITE_ON_FAIL=1 do-3_5_place_dp ; \
+		if [ $$? -ne 0 ]; then \
+			cp $(RESULTS_DIR)/3_5_place_dp.odb $(RESULTS_DIR)/3_place.odb ; \
+			$(SUB_MAKE) do-3_place.sdc ; \
+		else \
+			$(SUB_MAKE) do-3_place do-3_place.sdc ; \
+			echo >$(RESULTS_DIR)/place.ok 1 ; \
+		fi ; \
+	fi
+
+.PHONY: check-place
+check-place:
+	grep -q 1 $(RESULTS_DIR)/place.ok
 
 # Clean Targets
 #-------------------------------------------------------------------------------
@@ -740,10 +772,28 @@ $(eval $(call do-copy,5_route,5_3_route.odb))
 
 $(eval $(call do-copy,5_route,4_cts.sdc,,.sdc))
 
+# Same as do-place, support for build systems that require a non-zero exit code
+# and the same artifacts to be produced every time or no artifacts are published
 .PHONY: do-route
 do-route:
 	mkdir -p $(RESULTS_DIR) $(LOG_DIR) $(REPORTS_DIR)
-	$(UNSET_AND_MAKE) do-5_1_grt do-5_2_fillcell do-5_3_route do-5_route do-5_route.sdc
+	mkdir -p $(RESULTS_DIR) $(LOG_DIR) $(REPORTS_DIR)
+	echo >$(RESULTS_DIR)/route.ok 0
+	touch $(REPORTS_DIR)/congestion.rpt
+	touch $(REPORTS_DIR)/5_route_drc.rpt
+	@$(UNSET_VARS); \
+	$(SUB_MAKE) WRITE_ON_FAIL=1 do-5_1_grt ; \
+	if [ $$? -ne 0 ]; then \
+		cp $(RESULTS_DIR)/5_1_grt.odb $(RESULTS_DIR)/5_route.odb ; \
+		$(SUB_MAKE) do-5_route.sdc ; \
+	else \
+		$(SUB_MAKE) do-5_2_fillcell do-5_3_route do-5_route.sdc do-5_route ; \
+		echo >$(RESULTS_DIR)/route.ok 1 ; \
+	fi
+
+.PHONY: check-route
+check-route:
+	grep -q 1 $(RESULTS_DIR)/route.ok
 
 $(RESULTS_DIR)/5_route.v:
 	@export OR_DB=5_route ;\
