replace yamllint with yamlfix, add sanity check before commit in gh action
Signed-off-by: Jack Luar <jluar@precisioninno.com>

diff --git a/.github/workflows/github-actions-yaml-test.yml b/.github/workflows/github-actions-yaml-test.yml
--- a/.github/workflows/github-actions-yaml-test.yml
+++ b/.github/workflows/github-actions-yaml-test.yml
@@ -14,16 +14,15 @@ jobs:
       uses: actions/checkout@v4
       with:
         submodules: 'recursive'
-    - name: Run YAML script
+    - name: Run generate-variable-docs.py
       run: |
         python3 flow/scripts/generate-variable-docs.py
-    - name: Run YAML Lint
+    - name: Run yamlfix check
       run: |
-        pip install yamllint==1.35.1
-        yamllint flow/scripts/variables.yaml
+        yamlfix -c yamlfix.toml flow/scripts/variables.yaml --check
 
   docs-pr-update:
-    name: 'Create PR to update ORFS FlowVariables.md'
+    name: 'Create PR to update ORFS FlowVariables.md and variables.yaml'
     needs:
       - docs-test-job
     runs-on: ubuntu-latest
@@ -33,8 +32,12 @@ jobs:
     - name: Run generate-variable-docs.py
       run: |
         python3 flow/scripts/generate-variable-docs.py
+    - name: Run yamlfix
+      run: |
+        pip install yamlfix==1.17.0
+        yamlfix -c yamlfix.toml flow/scripts/variables.yaml
     - name: Create branch if diff exists
-      id: docs-update
+      id: variables-update
       run: |
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
@@ -43,15 +46,22 @@ jobs:
         else
           echo "has_update=false" >> "$GITHUB_OUTPUT"
         fi
-        git add .
+        git add flow/scripts/variables.yaml
+        git add docs/user/FlowVariables.md
         git commit --signoff -m "[Docs]: Update ORFS FlowVariables.md"
+
+        # Sanity check that no other files are unstaged
+        if [ -n "$(git status --porcelain)" ]; then
+          echo "Error: Unstaged changes after commit."
+          exit 1
+        fi
     - name: Only push if not master
       if: "github.event.client_payload.branch != 'master'"
-      id: remote-update-pr
+      id: variables-update-pr
       run: |
         git push origin "HEAD:refs/pull/${{ github.event.client_payload.branch }}/head"
-    - name: Create docs update PR
-      if: "steps.remote-update.outputs.has_update == 'true' && github.event.client_payload.branch == 'master'"
+    - name: Create variables update PR
+      if: "steps.variables-update.outputs.has_update == 'true' && github.event.client_payload.branch == 'master'"
       uses: peter-evans/create-pull-request@v5
       with:
         token: ${{ github.token }}
